@url=http://localhost:3000

@token=f1493c3c4ae339bc909c5d0e6bc7180e1e572c264e2c20387e54309d6e7bfcf67cdabb4648872d6562ebc41db8322e6e0c820423c6573d4b2bda077a3e0025944eccfbc8e68e2a397b364116117af07f4d8677b95abb0ad3cd8d82a46268e460d9f81ec463d70cfb109adf6772a026683cf17c04216f68c139bf3c59f949aee8
###
POST {{url}}/api/ingredients
Content-Type: application/json

{
  "data": {
    "name": "Tomate"
  }
}
###

POST {{url}}/api/ingredients
Content-Type: application/json  

{
  "data": {
    "name": "Mozzarella"
  }
}

###

POST {{url}}/api/ingredients
Content-Type: application/json  

{
  "data": {
    "name": "Basilic"
  }
}
### 
POST {{url}}/api/ingredients
Content-Type: application/json  

{
  "data": {
    "name": "Huile d'olive"
  }
}
### 
POST {{url}}/api/ingredients
Content-Type: application/json

{
  "data": {
    "name": "Sel"
  }
}