@url=http://localhost:3000

@token=f1493c3c4ae339bc909c5d0e6bc7180e1e572c264e2c20387e54309d6e7bfcf67cdabb4648872d6562ebc41db8322e6e0c820423c6573d4b2bda077a3e0025944eccfbc8e68e2a397b364116117af07f4d8677b95abb0ad3cd8d82a46268e460d9f81ec463d70cfb109adf6772a026683cf17c04216f68c139bf3c59f949aee8
###
GET {{url}}/api/recettes
Authorization: Bearer {{token}} 

###
POST {{url}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {

  "title": "Nouvelle recette",
  "preparationTime": 30,
  "difficulty": 2,
  "budget": 3,
  "description": "Une délicieuse nouvelle recette à essayer."
  }
}
###

### Fetch recipe data from external API (HTML response to parse)
GET https://encuisine.adrienrossignol.fr/recette/45
Accept: text/html

# L'indicqteur de budget, temps de prepartion et difficulte figure dans la page html sous forme d'icones a compterr
# temps_rouge.svg = 2 icones = 2
# difficulte_rouge.svg = 2 icones = 2
# budget_rouges.svg = 2 icone = 2


### Athenticate and obtain JWT token or signup new user
### This step is optional if you already have a valid token

### Create new user
POST {{url}}/auth/local/register
Content-Type: application/json

{
  "username": "foobar",
  "email": "foobar@example.com",
  "password": "foobarpassword"
}

### Authenticate existing user

POST {{url}}/auth/local
Content-Type: application/json

{
  "identifier": "foobar",
  "password": "foobarpassword"
}

### Create new recette in Strapi
POST {{url}}/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "Saucissés fumées, pomme de terre et champignons",
    "temps_de_preparation": 2,
    "difficulte": 2,
    "budget": 2,
    "description": "Cette recette s'effectue au Cookée. Couper les pommes de terre, les champignons, l'oignon et les saucisses. Mettre les pommes de terre 10 minutes en mode doré. Ajouter les saucisses et l'oignon. Mode doré 10 minutes. Ajouter les champignons, les aromates (herbes de Provence et ail) et l'eau. Cuire sous pression pendant 4 minutes. Ingrédients: 2 saucisses fumées, 4 pommes de terre, 200g de champignons, 1 oignon, 50ml d'eau."
  }
}

###

### Get all recettes to verify creation
GET {{url}}/api/recettes
Accept: application/json
Authorization: Bearer {{token}}

###

### Get specific recette by ID (replace {id} with actual ID)
GET {{url}}/api/recettes/{id}
Accept: application/json
Authorization: Bearer {{token}}


### Update specific recette by ID (replace {id} with actual ID)
PUT {{url}}/api/recettes/{id}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "description": "Updated description for the recipe."
  }
}


### Delete specific recette by ID (replace {id} with actual ID)
DELETE {{url}}/api/recettes/{id}
Accept: application/json
Authorization: Bearer {{token}}